---
- name: Setup
  hosts: all
  sudo : true
  tasks:
   - name: Add ansible user
     user:
      name: ansible
      state: present
      generate_ssh_keys: true
   - name: Ensure NTP is installed
     apt:
      name: ntp
      state: present
   - name: Ensure NTP is started
     service:
      name: ntp
      state: started
